import mammoth from "mammoth";
import { extractText as extractPdfText, getDocumentProxy } from "unpdf";

/**
 * Real text extraction for the composer's document-upload flow (`api/routes/documents.ts`)
 * — plain-text files (.txt/.md/.csv/.json/.log) never reach this at all (the web client
 * already reads those itself with `File.text()`, zero network round trip); this module
 * exists only for the two binary formats a browser can't parse on its own. `unpdf` (a
 * modern, ESM-native wrapper around Mozilla's own pdf.js, built for serverless/Node) and
 * `mammoth` (the standard DOCX-to-text library) are both real, actively-maintained parsers
 * — never a hand-rolled one, and never a byte-for-byte passthrough pretending a binary file
 * is plain text (Product Principle #4, "Never fake success"). Both were live-verified
 * against real files generated by `pdfkit`/`docx` (see
 * `test/documents/extractText.test.ts`) — a plain-text `pdf-parse@1.1.1` was tried first and
 * dropped: it crashes under this project's ESM module resolution (a known issue with its
 * bundled debug self-test) even after working around that, its ancient bundled pdf.js
 * (v1.10.100) truncated real multi-sentence text unpredictably.
 */
export type SupportedDocumentType = "pdf" | "docx";

const PDF_EXTENSIONS = [".pdf"];
const DOCX_EXTENSIONS = [".docx"];
const PDF_MIME = "application/pdf";
const DOCX_MIME = "application/vnd.openxmlformats-officedocument.wordprocessingml.document";

/** `null` means "not one of the binary formats this module handles" — the caller (the
 * route) treats that as unsupported, since plain-text types are handled client-side. */
export function classifyDocumentType(filename: string, mimeType: string): SupportedDocumentType | null {
  const lower = filename.toLowerCase();
  if (mimeType === PDF_MIME || PDF_EXTENSIONS.some((ext) => lower.endsWith(ext))) return "pdf";
  if (mimeType === DOCX_MIME || DOCX_EXTENSIONS.some((ext) => lower.endsWith(ext))) return "docx";
  return null;
}

/** Thrown on any extraction failure (corrupt file, password-protected PDF, unreadable
 * DOCX, ...) — the route maps this to one honest, non-technical message; the underlying
 * `cause` is for server-side logging only, never sent to the client. */
export class DocumentExtractionError extends Error {
  constructor(message: string, readonly cause?: unknown) {
    super(message);
    this.name = "DocumentExtractionError";
  }
}

export async function extractDocumentText(buffer: Buffer, type: SupportedDocumentType): Promise<string> {
  try {
    if (type === "pdf") {
      const pdf = await getDocumentProxy(new Uint8Array(buffer));
      const { text } = await extractPdfText(pdf, { mergePages: true });
      return text;
    }
    const result = await mammoth.extractRawText({ buffer });
    return result.value;
  } catch (err) {
    throw new DocumentExtractionError(`Failed to extract text from ${type} document`, err);
  }
}
